# Generated by Django 4.0.4 on 2022-07-18 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleRepModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('residential_address', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/sale_rep_images')),
                ('max_credit', models.FloatField()),
                ('credit', models.FloatField(blank=True, default=0)),
                ('crate_credit', models.FloatField(blank=True, default=0)),
                ('total_amount_bought', models.FloatField(blank=True, default=0)),
                ('status', models.CharField(blank=True, default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staffmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('residential_address', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/customer_images')),
                ('balance', models.FloatField(blank=True, default=0)),
                ('crate_balance', models.IntegerField(blank=True, default=0)),
                ('amount_bought', models.FloatField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staffmodel')),
            ],
        ),
    ]
